<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'A Demo User does not exist. You must <a href="/site/initialize"><strong>initialize</strong></a> the Demo Database from the menu. After this you will be automatically logged in as a <strong>demo</strong> user.'
    => 'Ein Demo Benutzer existiert nicht. Die Datenbank kann vom Menu <a href="/site/initialize"><strong>initialisiert</strong></a> werden. Danach wirst du als <strong>demo</strong> user automatisch eingeloggt.',
    'About' => 'Info',
    'Action' => 'Aktion',
    'Action Steps' => 'Aktionsschritte',
    'Activity - In the previous 7 days' => 'Aktivitaet - aus den vergangenen 7 Tagen',
    'An active board must be <a href="/board/select">selected</a> in order to proceed.'
    => 'Um weiter zu machen, muss ein Tafel <a href="/board/select">aktiviert werden</a>.',
    'Are you sure you want to delete this item?' => 'Willst du diesen Eintrag tatsaechlich loeschen?',
    'Backlog' => 'R&uuml;ckstand',
    'Ban The Can Administration' => 'Ban The Can Verwaltung',
    'Begin' => 'Anfang',
    'Board Columns' => 'Tafel Spalten',
    'Boards' => 'Tafeln',
    'Board ID' => 'Tafel-ID',
    'Columns' => 'Spalten',
    'Column ID' => 'Spalte-ID',
    'Completed' => 'Erledigt',
    'Contact' => 'Kontakt',
    'Create' => 'Speichern',
    'Create Task' => 'Neuer Aufgabe',
    'Create Board' => 'Neue Tafel',
    'Create Board Column' => 'Neue Tafelspalte',
    'Create Resolution' => 'Neuer Beschluss',
    'Create Site News' => 'Neue Site-Nachricht',
    'Create Tag' => 'Neues Stichwort',
    'Create Ticket' => 'Neues Ticket',
    'Create User' => 'Neuer Benutzer',
    'Create a fresh demo database including a demo user' => 'Erzeuge eine frische Demo-Datenbank und neuen demo-Benutzer',
    'Created At' => 'Eingetragen am',
    'Created By' => 'Eingetragen von',
    'Date' => 'Datum',
    'Delete' => 'Loeschen',
    'Description' => 'Beschreibung',
    'Edit' => 'Editieren',
    'End' => 'Ende',
    'Event' => 'Ereignis',
    'Frequency' => 'Haeufugkeit',
    'From Date' => 'Datum von',
    'Here you can edit all DB Tables used in the Front End' => 'Hier kannst du all DB Tabellen vom Frontend editieren',
    'ID' => 'ID',
    'If you forgot your password you can' => 'Beim vergessenen Passwort kannst du',
    'INITIALIZE USER DB' => 'Benutzer-Datenbank initialisieren',
    'Initialize Demo Database' => 'Demo-Datenbank initialisieren',
    'Login' => 'Einloggen',
    'Logout' => 'Ausloggen',
    'Name' => 'Name',
    'News' => 'Nachrichten',
    'Page Size:' => 'Tickets per Seite:',
    //'Please contact us if you think this is a server error. Thank you.' => '',
    'Please fill out the following fields to login as an Admin User:' => 'Folgende Felder bitte ausf&uuml;llen, um als Admin einzuloggen',
    'Please fill out the following fields to signup:' => 'Folgende Felder bitte ausfuellen, um neu anzumelden',
    'Protocol' => 'Protokoll',
    'Reset' => 'Zur&uuml;cksetzen',
    'reset it' => 'es zur&uuml;cksetzen',
    'Resolution' => 'Beschluss',
    'Resolutions' => 'Beschluesse',
    'Search' => 'Suche',
    'Select Board' => 'Tafel selektieren',
    'Signup' => 'Anmelden',
    'Site News' => 'Site-Nachrichten',
    'Table' => 'Tabelle',
    'Tags' => 'Stichwoerter',
    'Tag Search' => 'Stichwoertsuche',
    'Text Search' => 'Textsuche',
    'The above error occurred while the Web server was processing your request.' => 'Waehrend der Verarbeitung beim Server ist dieser Fehler aufgetreten.',
    'Ticket Backlog Configuration' => 'Ticket-Rueckstand Konfiguration',
    'Ticket Column Configuration' => 'Ticket-Spalten Konfiguration',
    'Ticket Completed Configuration' => 'Ticket-Erledigt Konfiguration',
    'Ticket Order' => 'Ticketfolge',
    'Title' => 'Titel',
    'To Date' => 'Datum bis',
    'Update' => 'Aktualisieren',
    'Update Tag' => 'Stichwort aktualisieren',
    'Update Ticket' => 'Ticket aktualisieren',
    'Updated At' => 'Aktualisiert am',
    'Updated By' => 'Aktualisiert von',
    'Use commas to separate tags' => 'Stichwoerter mit Kommas trennen',
    'User Search' => 'Benutzersuche',
    'User Settings' => 'Benutzer Einstellungen',
    'You are a member of more than one board.<br/> Select which board you want to use.'
    => 'Du geh&ouml;rst mehreren Tafeln.<br/>Eins muss selektiert werden.',
];
